# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "/applications/web"
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: monthly

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "cargo"
    directory: "/packages/cadmium"
    schedule:
      interval: monthly
  - package-ecosystem: "cargo"
    directory: "/packages/cadmium-macros"
    schedule:
      interval: monthly
  - package-ecosystem: "cargo"
    directory: "/applications/tauri"
    schedule:
      interval: monthly
