[package]
name = "cadmium-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["parsing", "derive"] }
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6.0"

[lib]
proc-macro = true
